// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"valsea/src/config"
	"valsea/src/data"
	"valsea/src/handler"
	"valsea/src/server"
	"valsea/src/service"
)

// Injectors from wire.go:

func BuildApp() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	repository := data.NewRepository()
	account := service.NewAccount(repository)
	handlerAccount := handler.NewAccount(account)
	transfer := service.NewTransfer(repository)
	handlerTransfer := handler.NewTransfer(transfer)
	serverServer := server.NewServer(configConfig, handlerAccount, handlerTransfer)
	app := &App{
		Config: configConfig,
		Server: serverServer,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config *config.Config
	Server *server.Server
}
